# Generated by Django 4.2.2 on 2023-06-11 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("country", models.CharField(default="null", max_length=30)),
                ("description", models.TextField()),
                ("popularPlaces", models.TextField()),
                ("image", models.ImageField(upload_to="images/")),
            ],
        ),
    ]
